### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by jfarcher** [njh/HeatingController#1]
Hi, 
noticed the CSS reference in the arduino file points to http://star.aelius.co.uk/boiler.css which gives a 404.

**Comment by njh** [comment]
I didn't imagine anyone would look at this repository! It is mostly for my own documentation.

The problem is that the web server isn't redirecting from HTTP to HTTPS correctly.
It was actually working for me because I had [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) turned on, which meant my browser wasn't even trying plain HTTP.

The CSS file is now here:
https://star.aelius.co.uk/heating-controller.css

Thanks for letting me know.
